In [1]:
import pandas as pd

In [2]:
# Import data file
data = pd.read_csv('US_counties_COVID19_health_weather_data.csv')
data.head()

/Users/jihyunmoon/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3051: DtypeWarning: Columns (190,202) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,lat,lon,...,min_temp_3d_avg,min_temp_5d_avg,min_temp_10d_avg,min_temp_15d_avg,dewpoint_3d_avg,dewpoint_5d_avg,dewpoint_10d_avg,dewpoint_15d_avg,date_stay_at_home_announced,date_stay_at_home_effective
0,2020-01-21,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,38.266667,38.92,38.44,36.146667,40.333333,41.64,40.74,37.973333,2020-03-23,2020-03-23
1,2020-01-22,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,39.233333,41.12,39.76,37.613333,42.633333,42.98,41.68,39.440000,2020-03-23,2020-03-23
2,2020-01-23,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,42.900000,41.74,41.15,38.226667,44.733333,43.72,42.47,40.120000,2020-03-23,2020-03-23
3,2020-01-24,Cook,Illinois,17031,1,0,no,no,41.840039,-87.816716,...,32.366667,30.02,27.43,24.886667,31.433333,28.50,25.00,22.693333,2020-03-20,2020-03-21
4,2020-01-24,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,...,44.600000,42.54,41.75,38.226667,46.000000,44.30,42.88,41.293333,2020-03-23,2020-03-23

In [3]:
# Keep columns needed for visuals
data_visuals = data.loc[:,:'total_population']
data_visuals.head()

,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,lat,lon,total_population
0,2020-01-21,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,758649
1,2020-01-22,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,758649
2,2020-01-23,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,758649
3,2020-01-24,Cook,Illinois,17031,1,0,no,no,41.840039,-87.816716,5227575
4,2020-01-24,Snohomish,Washington,53061,1,0,no,no,48.047489,-121.697307,758649

In [4]:
# Check columns with null values
data_visuals.columns[data_visuals.isna().any()].tolist()

[]