In [1]:
# Import dependencies
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import re
from sqlalchemy import create_engine
from sqlalchemy.sql import text
import psycopg2
from config import db_password
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
# Read the test dataset from Postgress database
try:
    db_string = f"postgres://postgres:#R6lifer@127.0.0.1:5432/final_project"
    engine = create_engine(db_string)
    print("Connection made WOOTWOOT!")
except:
    print('Could not connect to database')

Connection made WOOTWOOT!

In [3]:
# Read the data table
hw_df = pd.read_sql_query('SELECT * FROM covid_table;', engine)
locations = pd.read_sql_query('SELECT * FROM covid_table;', engine)
locations.head()

,index,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,total_population,...,percentile_rank_minorities,percentile_rank_limited_english_abilities,percentile_rank_minority_status_and_language_theme,percentile_rank_multi_unit_housing,percentile_rank_mobile_homes,percentile_rank_overcrowding,percentile_rank_no_vehicle,percentile_rank_institutionalized_in_group_quarters,percentile_rank_housing_and_transportation,percentile_rank_social_vulnerability
0,0,5/29/2020,Autauga,Alabama,1001,212,3,yes,yes,55049,...,0.6339,0.5355,0.5976,0.6791,0.7268,0.2477,0.3298,0.1251,0.2881,0.3773
1,1,5/29/2020,Baldwin,Alabama,1003,282,9,yes,yes,199510,...,0.5253,0.5282,0.5294,0.9733,0.5387,0.2639,0.0872,0.3438,0.3324,0.2757
2,2,5/29/2020,Barbour,Alabama,1005,147,1,yes,yes,26614,...,0.9042,0.6979,0.8558,0.2814,0.9370,0.4438,0.8816,0.9427,0.9312,0.9847
3,3,5/29/2020,Bibb,Alabama,1007,71,1,yes,yes,22572,...,0.6450,0.3553,0.5018,0.4072,0.9249,0.0248,0.5645,0.9156,0.6663,0.5737
4,4,5/29/2020,Blount,Alabama,1009,60,1,yes,yes,57704,...,0.4238,0.7482,0.5992,0.1344,0.8465,0.5056,0.1907,0.1515,0.1827,0.4986

In [4]:
locations = locations[["county", "state", "fips"]]
locations.head()

    county    state  fips
0  Autauga  Alabama  1001
1  Baldwin  Alabama  1003
2  Barbour  Alabama  1005
3     Bibb  Alabama  1007
4   Blount  Alabama  1009

In [5]:
hw_df = hw_df[['percent_american_indian_alaska_native',
 'percent_65_and_over',
 'percent_hispanic',
 'percent_native_hawaiian_other_pacific_islander',
 'overcrowding',
 'percent_unemployed_chr',
 'percent_not_proficient_in_english',
 'percent_female',
 'percent_uninsured',
 'percent_mobile_homes',
 'percent_disconnected_youth',
 'teen_birth_rate',
 'percent_non_hispanic_white',
 'percent_minorities',
 'average_number_of_mentally_unhealthy_days',
 'drug_overdose_mortality_rate',
 'percent_less_than_18_years_of_age',
 'percent_excessive_drinking',
 'percent_physically_inactive',
 'percent_low_birthweight']]

In [6]:
hw_df.head()

,percent_american_indian_alaska_native,percent_65_and_over,percent_hispanic,percent_native_hawaiian_other_pacific_islander,overcrowding,percent_unemployed_chr,percent_not_proficient_in_english,percent_female,percent_uninsured,percent_mobile_homes,percent_disconnected_youth,teen_birth_rate,percent_non_hispanic_white,percent_minorities,average_number_of_mentally_unhealthy_days,drug_overdose_mortality_rate,percent_less_than_18_years_of_age,percent_excessive_drinking,percent_physically_inactive,percent_low_birthweight
0,0.480207,15.562670,2.965774,0.111509,1.201923,3.629079,0.820225,51.448715,8.721686,18.0,10.269195,25.284927,74.308016,24.3,4.654031,10.809447,23.674035,15.026031,34.7,8.619529
1,0.772399,20.443350,4.646779,0.066966,1.270792,3.615382,0.543517,51.538377,11.333404,11.9,8.476795,27.880692,83.111337,16.8,4.304056,13.610487,21.607911,17.958310,26.5,8.345003
2,0.659137,19.420441,4.276355,0.184880,1.688596,5.171384,1.631683,47.216752,12.242792,29.9,13.339302,40.870815,45.641252,54.1,5.185594,16.071850,20.867328,12.844016,23.5,11.474559
3,0.437500,16.473214,2.625000,0.116071,0.255319,3.971828,0.268210,46.781250,10.206253,28.4,10.269195,41.696794,74.589286,25.2,4.551699,28.060433,20.477679,15.570042,33.5,10.308710
4,0.653527,18.236515,9.571231,0.121024,1.891368,3.511157,1.724520,50.726141,13.360759,22.9,18.941594,33.534595,86.886238,12.3,4.891455,24.199543,23.153527,14.230594,30.3,7.604563

In [7]:
hw_scaled_df = StandardScaler().fit_transform(hw_df)

In [8]:
pca = PCA(n_components=2)

In [9]:
hw_pca = pca.fit_transform(hw_scaled_df)

In [11]:
hw_pca_df = pd.DataFrame(data=hw_pca, columns=["PCA 1", "PCA 2"])

In [12]:
locations = locations.join(hw_pca_df)
locations.head()

    county    state  fips     PCA 1     PCA 2
0  Autauga  Alabama  1001  0.304595 -0.960460
1  Baldwin  Alabama  1003 -0.847396 -0.386804
2  Barbour  Alabama  1005  2.836492 -1.672889
3     Bibb  Alabama  1007  0.823771 -2.121239
4   Blount  Alabama  1009  0.952703 -1.627698

In [13]:
locations.to_csv("Visualized_Results.csv")