In [1]:
# Import dependencies
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
import re
from sqlalchemy import create_engine
from sqlalchemy.sql import text
import psycopg2
from config import db_password
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [2]:
# Read the test dataset from Postgress database
try:
    db_string = f"postgres://postgres:#R6lifer@127.0.0.1:5432/final_project"
    engine = create_engine(db_string)
    print("Connection made WOOTWOOT!")
except:
    print('Could not connect to database')

Connection made WOOTWOOT!

In [3]:
# Read the data table
hw_df = pd.read_sql_query('SELECT * FROM covid_table;', engine)
locations = pd.read_sql_query('SELECT * FROM covid_table;', engine)
locations.head()

,index,date,county,state,fips,cases,deaths,stay_at_home_announced,stay_at_home_effective,total_population,...,percentile_rank_minorities,percentile_rank_limited_english_abilities,percentile_rank_minority_status_and_language_theme,percentile_rank_multi_unit_housing,percentile_rank_mobile_homes,percentile_rank_overcrowding,percentile_rank_no_vehicle,percentile_rank_institutionalized_in_group_quarters,percentile_rank_housing_and_transportation,percentile_rank_social_vulnerability
0,0,5/29/2020,Autauga,Alabama,1001,212,3,yes,yes,55049,...,0.6339,0.5355,0.5976,0.6791,0.7268,0.2477,0.3298,0.1251,0.2881,0.3773
1,1,5/29/2020,Baldwin,Alabama,1003,282,9,yes,yes,199510,...,0.5253,0.5282,0.5294,0.9733,0.5387,0.2639,0.0872,0.3438,0.3324,0.2757
2,2,5/29/2020,Barbour,Alabama,1005,147,1,yes,yes,26614,...,0.9042,0.6979,0.8558,0.2814,0.9370,0.4438,0.8816,0.9427,0.9312,0.9847
3,3,5/29/2020,Bibb,Alabama,1007,71,1,yes,yes,22572,...,0.6450,0.3553,0.5018,0.4072,0.9249,0.0248,0.5645,0.9156,0.6663,0.5737
4,4,5/29/2020,Blount,Alabama,1009,60,1,yes,yes,57704,...,0.4238,0.7482,0.5992,0.1344,0.8465,0.5056,0.1907,0.1515,0.1827,0.4986

In [4]:
locations = locations[["county", "state", "fips"]]
locations.head()

    county    state  fips
0  Autauga  Alabama  1001
1  Baldwin  Alabama  1003
2  Barbour  Alabama  1005
3     Bibb  Alabama  1007
4   Blount  Alabama  1009

In [5]:
hw_df = hw_df[['percent_american_indian_alaska_native',
 'percent_native_hawaiian_other_pacific_islander',
 'percent_hispanic',
 'percent_not_proficient_in_english',
 'percent_65_and_over',
 'percent_female',
 'teen_birth_rate',
 'percent_unemployed_chr',
 'percent_uninsured',
 'overcrowding',
 'percent_less_than_18_years_of_age',
 'income_ratio',
 'primary_care_physicians_rate',
 'percentile_rank_single_parent_households',
 'percent_driving_deaths_with_alcohol_involvement',
 'percent_single_parent_households_cdc',
 'percent_minorities',
 'percent_homeowners',
 'percentile_rank_minorities',
 'drug_overdose_mortality_rate']]

In [6]:
hw_df.head()

,percent_american_indian_alaska_native,percent_native_hawaiian_other_pacific_islander,percent_hispanic,percent_not_proficient_in_english,percent_65_and_over,percent_female,teen_birth_rate,percent_unemployed_chr,percent_uninsured,overcrowding,percent_less_than_18_years_of_age,income_ratio,primary_care_physicians_rate,percentile_rank_single_parent_households,percent_driving_deaths_with_alcohol_involvement,percent_single_parent_households_cdc,percent_minorities,percent_homeowners,percentile_rank_minorities,drug_overdose_mortality_rate
0,0.480207,0.111509,2.965774,0.820225,15.562670,51.448715,25.284927,3.629079,8.721686,1.201923,23.674035,5.234597,45.04180,0.3200,26.785714,7.3,24.3,74.894625,0.6339,10.809447
1,0.772399,0.066966,4.646779,0.543517,20.443350,51.538377,27.880692,3.615382,11.333404,1.270792,21.607911,4.417767,72.89727,0.1493,30.769231,6.0,16.8,73.619343,0.5253,13.610487
2,0.659137,0.184880,4.276355,1.631683,19.420441,47.216752,40.870815,5.171384,12.242792,1.688596,20.867328,5.681410,31.65809,0.9296,40.000000,12.4,54.1,61.397779,0.9042,16.071850
3,0.437500,0.116071,2.625000,0.268210,16.473214,46.781250,41.696794,3.971828,10.206253,0.255319,20.477679,4.368581,48.52656,0.3266,27.586207,7.3,25.2,75.073099,0.6450,28.060433
4,0.653527,0.121024,9.571231,1.724520,18.236515,50.726141,33.534595,3.511157,13.360759,1.891368,23.153527,4.430262,22.40877,0.4018,19.444444,7.8,12.3,78.626214,0.4238,24.199543

In [7]:
hw_scaled_df = StandardScaler().fit_transform(hw_df)

In [8]:
pca = PCA(n_components=1)

In [9]:
hw_pca = pca.fit_transform(hw_scaled_df)

In [10]:
hw_pca_df = pd.DataFrame(data=hw_pca, columns=["PCA"])

In [11]:
locations = locations.join(hw_pca_df)
locations.head()

    county    state  fips       PCA
0  Autauga  Alabama  1001 -0.451852
1  Baldwin  Alabama  1003 -1.468931
2  Barbour  Alabama  1005  2.522901
3     Bibb  Alabama  1007 -0.770812
4   Blount  Alabama  1009 -0.645776

In [12]:
locations.to_csv("Visualized_Results.csv")